language: python

python:
  - "3.6"

stages:
  - Test
  - Nightly

before_install: &before_install
  - time

install: true


jobs:
  include:
    - stage: Test
      script: python --version

    - stage: Nightly
      python: "3.6"
      if: branch = nightly
      # Use previously defined before_install
      before_install: *before_install
      install:
        # Merge master into nightly
        - git log --oneline --graph --decorate
        - git checkout nightly
        - git fetch origin master
        - git rebase FETCH_HEAD
        - git log --oneline --graph --decorate
        # Copy "nightly" files
        - cp nightly/setup_nightly.py setup.py
        # Push to nightly branch
        - git remote rm origin && git remote add origin https://$GITHUB_TOKEN@github.com/${TRAVIS_REPO_SLUG}.git
        - git push origin nightly
      script: true
